model: deepseek-coder:6.7b
auto:
  max_iterations: 3
  dry_run: false
  require_tests_green: true
  confirmation_threshold: 0.7
  allowlist:
    - "app/**"
    - "lib/**"
    - "spec/**"
    - "config/**"
    - "db/**"
    - "src/**"
  denylist:
    - ".git/**"
    - "node_modules/**"
    - "log/**"
    - "tmp/**"
    - "dist/**"
    - "build/**"
index:
  threads: 8
  globs:
    - "**/*.{rb,erb,haml,slim,js,jsx,ts,tsx,rb,ru}"
