provider: ollama
# Default models (Ollama)
#
# For best results, use code-specific instruct models for planner/developer.
model: "qwen2.5-coder:7b-instruct"
planner_model: "qwen2.5-coder:7b-instruct"
developer_model: "qwen2.5-coder:7b-instruct"
reviewer_model: "llama3.1:8b-instruct"
auto:
  max_iterations: 3
  dry_run: false
  require_tests_green: true
  confirmation_threshold: 0.7
  allowlist:
    - "app/**"
    - "lib/**"
    - "spec/**"
    - "config/**"
    - "db/**"
    - "src/**"
  denylist:
    - ".git/**"
    - "node_modules/**"
    - "log/**"
    - "tmp/**"
    - "dist/**"
    - "build/**"
index:
  threads: 8
  globs:
    - "**/*.{rb,erb,haml,slim,js,jsx,ts,tsx,rb,ru}"
