provider: ollama
# Default models (Ollama)
#
# BENCHMARK RESULTS (see script/benchmark_models.rb):
# 🥇 qwen2.5-coder:1.5b - 4/4 score, 0.57s latency (FASTEST + RELIABLE) - RECOMMENDED
# 🥈 qwen2.5-coder:7b-instruct-q5_K_M - 3/4 score, 4.6s latency (BEST QUALITY)
# 🥉 llama3.1:8b-instruct-q4_K_M - 3/4 score, 4.8s latency (STRONG BACKUP)
# ⚠️  starcoder2:3b - 1/4 score, timeout issues (AVOID)
#
# MODEL SELECTION STRATEGY:
# - Speed tasks (chat, explain, quick edits): qwen2.5-coder:1.5b
# - Quality tasks (agent mode, refactors, multi-file): qwen2.5-coder:7b-instruct-q5_K_M
# - Heavy tasks (complex migrations): llama3.1:8b-instruct-q4_K_M
#
# For best results, use code-specific models for developer_model and planner_model
model: "qwen2.5-coder:1.5b" # Benchmark winner: fastest + reliable (4/4 score, 0.57s)
planner_model: "qwen2.5-coder:1.5b" # Fast JSON/structured planning
developer_model: "qwen2.5-coder:7b-instruct-q5_K_M" # Quality model for code generation (3/4 score)
reviewer_model: "mistral:7b-instruct" # Good for code review and analysis
embed_model: "nomic-embed-text:latest" # Embedding model (use :latest tag for latest version)

# OpenAI models (use with --provider openai)
# Uncomment to use OpenAI models by default:
# model: "gpt-4o-mini"
# planner_model: "gpt-4o-mini"
# developer_model: "gpt-4o-mini"
# reviewer_model: "gpt-4o"
# embed_model: "text-embedding-3-small"
ollama:
  # Note: Ollama host is resolved globally (CLI/ENV/~/.devagent.yml/default), not from this project file.
  params:
    temperature: 0.2
    top_p: 0.95
openai:
  # Use Ollama's OpenAI-compatible API (for embeddings)
  uri_base: "http://localhost:11434/v1"
  api_key: "ollama" # Dummy key for Ollama
  request_timeout: 600
  params:
    temperature: 0.2
    top_p: 0.95
  options:
    num_gpu: 0
    num_ctx: 2048
auto:
  max_iterations: 3
  dry_run: false
  require_tests_green: true
  confirmation_threshold: 0.7
  command_allowlist:
    - "bundle"
    - "ruby"
    - "rubocop"
    - "rake"
    - "rspec"
    - "make"
  allowlist:
    - "app/**"
    - "lib/**"
    - "spec/**"
    - "config/**"
    - "db/**"
    - "src/**"
    - "bin/**"
    - "exe/**"
    - "README*" # Allow reading documentation files (works for any project type)
    - "docs/**" # Allow reading documentation directories
  denylist:
    - ".git/**"
    - "node_modules/**"
    - "log/**"
    - "tmp/**"
    - "dist/**"
    - "build/**"
    - ".env*"
    - "config/credentials*"
index:
  threads: 8
  globs:
    - "**/*.{rb,rbs,ru,erb,haml,slim,js,jsx,ts,tsx}"
    - "**/*.{md,mdx,txt}" # Include documentation files for better context
  chunk_size: 1800
  overlap: 200
memory:
  short_term_turns: 20
