model: "llama3.1:8b"
auto:
  max_iterations: 3
  dry_run: false
  require_tests_green: true
  confirmation_threshold: 0.7
  allowlist:
    - "**/*"
    - "lib/**"
    - "spec/**"
    - "sig/**"
    - "bin/**"
    - "exe/**"
    - "**.md"
  denylist:
    - ".git/**"
    - "node_modules/**"
    - "log/**"
    - "tmp/**"
    - "dist/**"
    - "build/**"
index:
  threads: 8
  globs:
    - "**/*.{rb,rbs,ru,erb,haml,slim,js,jsx,ts,tsx}"
