provider: ollama
# Default models (Ollama)
# Model recommendations for devagent:
#
# BEST FOR CODE GENERATION & STRUCTURED OUTPUTS:
# - deepseek-coder:6.7b (excellent for code, JSON, diffs) - RECOMMENDED
# - codellama:7b-instruct (Meta's code model, good for structured outputs)
# - qwen2.5-coder:7b (good instruction following, code-focused)
#
# GOOD ALTERNATIVES:
# - mistral:7b-instruct (excellent instruction following, good for planning)
# - llama3.1:8b-instruct (balanced, but not code-specific)
# - llama3.2:3b (TOO SMALL - avoid for planning/diff generation)
#
# For best results, use code-specific models for developer_model and planner_model
model: "deepseek-coder:6.7b" # Code-focused model, excellent for structured outputs
planner_model: "deepseek-coder:6.7b" # Code models handle JSON/structured planning well
developer_model: "deepseek-coder:6.7b" # Code models generate better diffs
reviewer_model: "mistral:7b-instruct" # Good for code review and analysis
embed_model: "nomic-embed-text"

# OpenAI models (use with --provider openai)
# Uncomment to use OpenAI models by default:
# model: "gpt-4o-mini"
# planner_model: "gpt-4o-mini"
# developer_model: "gpt-4o-mini"
# reviewer_model: "gpt-4o"
# embed_model: "text-embedding-3-small"
ollama:
  # Note: Ollama host is resolved globally (CLI/ENV/~/.devagent.yml/default), not from this project file.
  params:
    temperature: 0.2
    top_p: 0.95
openai:
  # Use Ollama's OpenAI-compatible API (for embeddings)
  uri_base: "http://localhost:11434/v1"
  api_key: "ollama" # Dummy key for Ollama
  request_timeout: 600
  params:
    temperature: 0.2
    top_p: 0.95
  options:
    num_gpu: 0
    num_ctx: 2048
auto:
  max_iterations: 3
  dry_run: false
  require_tests_green: true
  confirmation_threshold: 0.7
  command_allowlist:
    - "bundle"
    - "ruby"
    - "rubocop"
    - "rake"
    - "rspec"
    - "make"
  allowlist:
    - "app/**"
    - "lib/**"
    - "spec/**"
    - "config/**"
    - "db/**"
    - "src/**"
    - "bin/**"
    - "exe/**"
    - "README*" # Allow reading documentation files (works for any project type)
    - "docs/**" # Allow reading documentation directories
  denylist:
    - ".git/**"
    - "node_modules/**"
    - "log/**"
    - "tmp/**"
    - "dist/**"
    - "build/**"
    - ".env*"
    - "config/credentials*"
index:
  threads: 8
  globs:
    - "**/*.{rb,rbs,ru,erb,haml,slim,js,jsx,ts,tsx}"
    - "**/*.{md,mdx,txt}" # Include documentation files for better context
  chunk_size: 1800
  overlap: 200
memory:
  short_term_turns: 20
