#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require "bundler/setup"
rescue LoadError
  # allow running without bundler in installed gem contexts
end

require_relative "../lib/devagent"
Devagent::CLI.start(ARGV)
